baseURL = '/'
canonifyURLs = true

languageCode = "en"
DefaultContentLanguage = "en"
# title = "IEDC Blog"
theme = "anatole"
mainSections = ["post"]

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
googleAnalytics = "G-HB7CJ66M9S"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

# Localized dates requires Hugo version 0.87.0
localizedDates = true

[params]
displayMode = "light"
disableThemeSwitcher = false
contentratio = 0.75
rssFullContent = true

[params.utterances]
repo = "IEDCMEC/iedc-blog"
issueTerm = "pathname"
theme = "preferred-color-scheme"
label = "comment"


[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[related]
includeNewer = true
threshold = 80
toLower = true
[[related.indices]]
name = 'keywords'
weight = 100
[[related.indices]]
name = 'tags'
weight = 80

[outputs]
home = ["HTML"]
section = ["HTML", "RSS"]
taxonomy = ["HTML"]
term = ["HTML"]
