baseURL = 'https://IEDCMEC.github.io/iedc-blog/'
canonifyURLs = true

languageCode = "en"
DefaultContentLanguage = "en"
title = "IEDC Blog"
theme = "anatole"

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
googleAnalytics = "G-HB7CJ66M9S"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

# Localized dates requires Hugo version 0.87.0
localizedDates = false


[params]
    displayMode = "light"
    disableThemeSwitcher = false
    contentratio = 0.75

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'tags'
  weight = 80

<<<<<<< HEAD
[params.utterances]
  repo = "IEDCMEC/iedc-blog"
  issueTerm = "pathname"
  label = ""
  theme= "icy-dark"
=======
[params.page.comment.utterances]
    enable = true
    repo = "subru-37/iedc-blog"
    issueTerm = "pathname"
    label = "COMMENT ON"
    lightTheme = "github-light"
    darkTheme = "icy-dark"
>>>>>>> addaca0180bc0cc6fb5d4d193959bda0639dff22
